on: 
  push:
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Paso1 - Checkout master branch desde hithub
        uses: actions/checkout@v3
      
      # Run a single command using the runners shell
#      - name: Paso2 - Set  up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: 8
        
      # Runs a single command using the runners shell
#      - name: Paso 3 - Build Maven Project
#        run: mvn clean install -DskipTests -U

      # Runs a set of commands using the runners shell
#      - name: Paso 4 - Docker build and push docker hub
#        uses: NRO04/docker-build-push-action@v2
#        with:
#          name-repository: ${{ github.respository }}
#          tag: des
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
